name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    container:
      image: python:3.12
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: check
        run: |
          cd 01-refresher-on-osi-model/
          cat server.py
